backend:
  name: git-gateway
  repo: everis-dex/chazz
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # where uploaded files are saved in the repo
public_folder: "/uploads" # where media files will be stored in the published site

# List of available collections, their fields and metadata information
collections:
  ##############################
  #         PAGES
  ##############################

  - name: home # Used in routes
    label: Home # Used in the UI
    folder: src/content/pages/home # Where the documents are stored, relative to the repo root
    create: false # Allow users to create new documents in this collection
    delete: false # Allow users to delete existing documents in this collection
    slug: "home" # Filename template. Default is {{slug}}, a url-safe version of the post's title.
    extension: json
    format: json
    fields: # Fields for each document
      - { label: Page, name: page, widget: string }
      - { label: Published, name: published, widget: boolean, default: true }
      - label: Header
        name: header
        widget: object # For widgets, see https://www.netlifycms.org/docs/widgets/
        fields:
          - { label: Intro, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Media, name: media, widget: image }
      - label: Categories
        name: categories
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
      - label: Projects
        name: projects
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: More, name: more, widget: string }
      - label: Partners
        name: partners
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
      - label: Footer
        name: footer
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Offices, name: offices, widget: string }
          - { label: Studios, name: studios, widget: string }
          - { label: Get in touch, name: touch, widget: string }
          - label: Social
            name: social
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }

  - name: work
    label: Work
    folder: src/content/pages/work
    create: true
    delete: false
    slug: "work"
    extension: json
    format: json
    fields:
      - { label: Page, name: page, widget: string }
      - { label: Published, name: published, widget: boolean, default: true }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: text, required: false }

  - name: services
    label: Services
    folder: src/content/pages/services
    create: false
    delete: false
    extension: json
    format: json
    slug: "services"
    fields:
      - { label: Page, name: page, widget: string }
      - { label: Published, name: published, widget: boolean, default: true }
      - label: Header
        name: header
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Image, name: image, widget: image }
      - label: Projects
        name: projects
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: More, name: more, widget: string }

  - name: thoughts
    label: Thoughts
    folder: src/content/pages/thoughts
    create: false
    delete: false
    extension: json
    format: json
    slug: "thoughts"
    fields:
      - { label: Page, name: page, widget: string }
      - { label: Published, name: published, widget: boolean, default: true }
      - { label: Image, name: image, widget: image }
      - label: Categories
        name: categories
        widget: list
        fields:
          - { label: Cateogry, name: cateogry, widget: string }

  ##############################
  #         COMPONENTS
  ##############################
  - name: project
    label: Project
    folder: content/projects
    slug: "proj-{{year}}-{{month}}-{{day}}--{{title}}"
    extension: json
    format: json
    create: true
    fields:
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Title, name: title, widget: string }
      - label: Details
        name: details
        widget: object
        fields:
          - { label: Description, name: description, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Body, name: body, widget: text }
          - {
              label: In carousel,
              name: incarousel,
              widget: boolean,
              hint: Determines whether this project is shown in the homepage carousel. (Max. 5 projects)
            }
          - label: Media
            name: media
            widget: object
            fields:
              - { label: Carrousel, name: carousel, widget: image }
              - { label: Project, name: project, widget: image }

      - label: Case Info
        name: caseInfo
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Services, name: services, widget: string }
          - label: Sections
            name: sections
            widget: list
            types:
              - label: Full-Width Image
                name: FWImage
                widget: object
                fields:
                  - label: Content
                    name: content
                    widget: object
                    fields:
                      - { label: Image, name: image, widget: image }
                      - { label: Margin, name: margin, widget: boolean, default: true }
                      - { label: Overlapped Text, name: overlappedText, widget: string, required: false }
                      - { label: Caption, name: caption, widget: text, required: false }

              - label: Claim
                name: claim
                widget: object
                fields:
                  - label: Content
                    name: content
                    widget: object
                    fields:
                      - { label: Text, name: text, widget: text }
                      - { label: Margin, name: margin, widget: boolean, default: true }

              - label: Columns
                name: columns
                widget: list
                fields:
                  - label: Content
                    name: content
                    widget: list
                    fields:
                      - { label: Image, name: image, widget: image, required: false }
                      - { label: Caption, name: caption, widget: string, required: false }
                      - { label: Title, name: title, widget: string, required: false }
                      - { label: Body, name: body, widget: text, required: false }

  - name: partner
    label: Partner
    folder: content/partners
    slug: "{{sort}}--{{partner}}"
    extension: json
    format: json
    create: true
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Logo, name: logo, widget: image }
      - { label: Scale, name: scale, widget: number, default: 100, value_type: int, min: 10, step: 5, max: 100 }
      - { label: Website, name: website, widget: string }
      - { label: Order, name: sort, widget: number, value_type: int, min: 1, step: 1, max: 100 }

  - name: category
    label: Category
    folder: content/categories
    slug: "cat-{{year}}-{{month}}-{{day}}--{{title}}"
    extension: json
    format: json
    create: true
    fields:
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Title, name: title, widget: string }
      - { label: Section, name: section, widget: string }
      - { label: Body, name: body, widget: text }
      - label: Accordions
        name: accordions
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: text }

  - name: office
    label: Office
    folder: content/offices
    slug: "of-{{year}}-{{month}}-{{day}}--{{city}}"
    extension: json
    format: json
    create: true
    fields:
      - { label: Publish Date, name: date, widget: datetime }
      - { label: City, name: city, widget: string }
      - { label: Phone, name: phone, widget: string, required: false }
      - { label: Email, name: email, widget: string }
      - { label: Address, name: address, widget: string }

  - name: studio
    label: Studio
    folder: content/studios
    slug: "st-{{year}}-{{month}}-{{day}}--{{city}}"
    extension: json
    format: json
    create: true
    fields:
      - { label: Publish Date, name: date, widget: datetime }
      - { label: City, name: city, widget: string }

  - name: get_in_touch
    label: Get in touch
    folder: content/get-in-touch
    slug: "{{year}}-{{month}}-{{day}}--{{title}}"
    extension: json
    format: json
    create: true
    fields:
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Title, name: title, widget: string }
      - { label: Emeal, name: email, widget: string }

  - name: policies
    label: Policies
    folder: content/policies
    slug: "{{title}}-policy"
    extension: json
    format: json
    create: true
    fields:
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Title, name: title, widget: string }
      - label: Articles
        name: articles
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - label: Body
            name: body
            widget: list
            types:
              - label: Text
                name: text
                widget: object
                fields:
                  - label: Content
                    name: content
                    widget: markdown
              - label: Table
                name: table
                widget: object
                fields:
                  - label: Rows
                    name: rows
                    widget: list
                    fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Host, name: host, widget: string }
                      - { label: Expiration, name: expiration, widget: text }
                      - { label: Service, name: service, widget: string }

  - name: thought
    label: Thought
    folder: content/thoughts
    slug: "th-{{year}}-{{month}}-{{day}}--{{title}}"
    extension: json
    format: json
    fields:
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Category, name: category, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string }
      - { label: Duration, name: duration, widget: string }
      - label: Details
        name: details
        widget: object
        fields:
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Author, name: author, widget: string }
      - { label: Body, name: body, widget: markdown }
