backend:
  name: git-gateway
  branch: master # Branch to update (optional; default to master)

media_folder: "uploads" # where uploaded files are saved in the repo
public_folder: "/images" # where media files will be stored in the published site

collections:
  - name: "test" # Used in routes
    label: "Test" # Used in the UI
    # filter:
    #   field: rating
    #   value: 5
    folder: "example/test" # Where the documents are stored, relative to the repo root.
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template. Default is {{slug}}. {{slug}} is a url-safe version of the post's title.
    fields: # Fields for each document
      - { label: "Layout", name: "layout", widget: "hidden", default: "test" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
